FROM ros:noetic-ros-base

RUN apt-get update && apt-get install -y \
    python3-pip python3-cv-bridge python3-numpy \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /dummy
COPY dummy.py .

CMD ["bash", "-c", "source /opt/ros/noetic/setup.bash && python3 dummy.py"]
